name: frontend
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  rxdart: ^0.27.7
  
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  image: ^4.1.3
  dio: ^5.4.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  raised_buttons: ^0.0.2
  video_player: ^2.8.1
  video_player_win: ^2.3.4
  http: ^0.13.6
  flutter_vlc_player: ^7.4.0
  flutter_mjpeg: ^2.0.4
  flutter_hooks: ^0.20.3
  web_socket_channel: ^2.4.0
  socket_io_client: ^2.0.3+1
  file_picker: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

 
  assets:
    - assets/
    - assets/image/microdust_inform_background_black.jpg
    - assets/logo/
    - assets/logo/waitlogo_01.svg


  

